### ISSUE TITLE
SHA1 deprecation notice

### ISSUE THREAD

**Issue by Alhadis** [bramstein/homebrew-webfonttools#8]
I keep getting these deprecation notices whenever I update:

<img src="https://cloud.githubusercontent.com/assets/2346707/17273789/678f0a32-5706-11e6-9369-89981bf9393f.png" width="650" alt="Figure 1" />

**Comment by Chen-tao** [comment]
Please update your formula to sha256 as this issue @bramstein then fix this bug.
info as this issue [openresty's fix](https://github.com/killercup/homebrew-openresty/issues/25)

**Comment by cameronmalek** [comment]
Replicated the deprecation notices in plaintext here for convenience.

```
$ brew install sfnt2woff
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff.rb:6:in `<class:Sfnt2woff>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff.rb:6:in `<class:Sfnt2woff>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff.rb:6:in `<class:Sfnt2woff>'
```

```
$ brew install sfnt2woff-zopfli
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in `<class:Sfnt2woffZopfli>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in `<class:Sfnt2woffZopfli>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfnt2woff-zopfli.rb:7:in `<class:Sfnt2woffZopfli>'
```
